micronaut:
  application:
    name: exampleMicronautStarter
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
redis.uri: redis://localhost
vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: postgres
      user: postgres
      password: postgres
      maxSize: 5
